openapi: 3.0.0
info:
  title: Posyandu Child Nutrition Monitoring API
  description: API untuk aplikasi mobile pendataan dan monitoring kesehatan anak di posyandu.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local Development Server

paths:
  /api/v1/auth/login:
    post:
      summary: Login untuk pengguna
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Login berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  token:
                    type: string
                    example: "jwt-token"
                  expires_in:
                    type: integer
                    example: 3600
        '401':
          description: Login gagal
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Invalid credentials

  /api/v1/auth/register:
    post:
      summary: Registrasi pengguna baru
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
                full_name:
                  type: string
                  example: "John Doe"
                role:
                  type: string
                  example: "kader"
                posyandu_id:
                  type: string
                  example: "UUID-posyandu"
      responses:
        '201':
          description: Pengguna berhasil didaftarkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Kesalahan validasi atau pengguna sudah ada
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: User already exists

  /api/v1/anak/register:
    post:
      summary: Pendaftaran anak baru di posyandu
      tags:
        - Anak
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                NIK_anak:
                  type: string
                  example: "1234567890123456"
                nama_anak:
                  type: string
                  example: "Jane Doe"
                tempat_lahir:
                  type: string
                  example: "Jakarta"
                tgl_lahir:
                  type: string
                  format: date
                  example: "2020-01-01"
                jenis_kelamin:
                  type: string
                  example: "L"
                BB_lahir:
                  type: number
                  example: 3.2
                TB_lahir:
                  type: number
                  example: 50
                LILA:
                  type: number
                  example: 11.5
                LP:
                  type: number
                  example: 33
                cara_lahir:
                  type: string
                  example: "Normal"
                ASI_ekslusif:
                  type: boolean
                  example: true
                MPASI:
                  type: boolean
                  example: false
                UUID_ibu:
                  type: string
                  example: "UUID-ibu"
                UUID_ayah:
                  type: string
                  example: "UUID-ayah"
                posyandu_id:
                  type: string
                  example: "UUID-posyandu"
      responses:
        '201':
          description: Anak berhasil didaftarkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Anak registered successfully
                  anak_id:
                    type: string
                    example: "UUID-anak"
        '400':
          description: Kesalahan validasi atau NIK sudah terdaftar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Validation error or NIK already exists

  /api/v1/anak/{anak_id}/pemeriksaan:
    post:
      summary: Pengisian data pemeriksaan anak
      tags:
        - Pemeriksaan
      parameters:
        - name: anak_id
          in: path
          required: true
          schema:
            type: string
          example: "UUID-anak"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tinggi_badan:
                  type: number
                  example: 80
                berat_badan:
                  type: number
                  example: 12.5
                lingkar_lengan_atas:
                  type: number
                  example: 11.2
                lingkar_kepala:
                  type: number
                  example: 34.5
                tanggal_pemeriksaan:
                  type: string
                  format: date
                  example: "2024-01-01"
                catatan_kesehatan:
                  type: string
                  example: "Catatan tambahan"
                petugas_id:
                  type: string
                  example: "UUID-petugas"
      responses:
        '201':
          description: Pemeriksaan berhasil disimpan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Pemeriksaan recorded successfully
                  pemeriksaan_id:
                    type: string
                    example: "UUID-pemeriksaan"
        '400':
          description: Kesalahan validasi atau anak tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Anak not found or validation error